# Class path : com.thera.thermfw.util.Replacement
# Class name : REPLACEMENT
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.softre.thip.vendite.uds.YEvasioneUdsVendita', 'it.fornacecalandra.thip.vendite.uds.YEvasioneUdsVendita', '0', 'N', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.softre.thip.vendite.uds.YEvasioneUdsVenRiga', 'it.fornacecalandra.thip.vendite.uds.YEvasioneUdsVenRiga', '0', 'N', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it/softre/thip/vendite/uds/IntestazioneGrigliaSingolaRigaEvasione.jsp', 'it/fornacecalandra/thip/vendite/uds/IntestazioneGrigliaSingolaRigaEvasione.jsp', '2', 'N', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it/softre/thip/vendite/uds/SoftreDettaglioGrigliaSingolaRigaEvasione.jsp', 'it/fornacecalandra/thip/vendite/uds/SoftreDettaglioGrigliaSingolaRigaEvasione.jsp', '2', 'N', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('YEvasioneUdsVenRiga', 'YEvasioneUdsVenRigaCaland', '1', 'N', 'N');